#Trae la imagen python
FROM python:3 
#Agrega el archivo en el directorio raiz de la stancia
ADD holamundo.py /
#Ejecuta un comando dentro de la instancia,solo puede haber una en el dockerfile
CMD [ "python","./holamundo.py" ]
